In [6]:
# Indexing 1-D arrays
import numpy as np
a = np.arange(1,11)
print(a)
print(a[0])
print(a[[0,4,6]]) #prints 0th,4th and 6th
print(a[0:])
print(a[:3])
print(a[0:10:2])
print(a[0::2])
print(a[0:10:3])

[ 1  2  3  4  5  6  7  8  9 10]
1
[1 5 7]
[ 1  2  3  4  5  6  7  8  9 10]
[1 2 3]
[1 3 5 7 9]
[1 3 5 7 9]
[ 1  4  7 10]


In [14]:
# Indexing  multi-Dimensional
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print(a[0])
print(a[0,1])
print(a[1])
print(a[1,0])
print(a[0,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3]
2
[4 5 6]
4
3
