In [1]:
# Importing a numpy
import numpy as np
np.__version__

'1.26.2'

- Difference between a list and a array?
- - The elements in a list are of different datatypes.
- - The elements in a array must be of same datatypes.

In [2]:
# Creating 1-dimensional array
a = np.array([1,2,3,4,5,6,7])
print(type(a))
print(a)

<class 'numpy.ndarray'>
[1 2 3 4 5 6 7]


##### Basic Methods
- a.shape------->Gives number of elements in form of tuple as (rows, columns)
- np.size(a)-------->Gives total number of elements in an array
- len(a)------------>Gives no of rows in an array.
- a.ndim------------>Gives dimension of an array
- a.dtype----------->Gives datatype

In [3]:
a = np.array([1,2,3,4,5,6])
print(a.shape)
print(np.size(a))
print(a.ndim)
print(len(a))
print(a.dtype)

(6,)
6
1
6
int64


In [4]:
# Creating 2-Dimensional arrays
b = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(b)
print(b.dtype)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
int64


In [5]:
c = np.array([['a','b','c'],['d','e','f'],['g','h','i'],['j','k','l']])
print(c)
print(type(c))
print(c.shape)
print(c.ndim)
print(len(c))
print(np.size(c))
print(c.dtype)

[['a' 'b' 'c']
 ['d' 'e' 'f']
 ['g' 'h' 'i']
 ['j' 'k' 'l']]
<class 'numpy.ndarray'>
(4, 3)
2
4
12
<U1


In [6]:
# Creating 3-Dimensional arrays
a = np.arange(24).reshape(2,3,4)

#'4' is no. of inner elements
#'3' is no. of rows(inner)
#'2' is no. of rows(outer) 

print(a)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [8]:
# Creating 1-D array using arange()
x = np.arange(10)
print(x)
print(type(x))
print(x.shape)
print(np.size(x))
print(x.ndim)
print(len(x))
print(x.dtype)

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
(10,)
10
1
10
int64


In [13]:
# reshape()
# it is used to change dimension of an array
x = np.arange(10)
print(x)
print(x.ndim)
print(x.reshape(2,5))


[0 1 2 3 4 5 6 7 8 9]
1
[[0 1 2 3 4]
 [5 6 7 8 9]]


- Note:
- -  for 2-Dimension(row,column)
For 2-D arrays:
axis = 0 refers to rows
axis = 1 refers to columns
- -  for 3-Dimension(outer row, inner row, column)

In [17]:
z = np.arange(1,13).reshape(3,4) # 2 operations can be done
print(z)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [18]:
# To return sum of z
z.sum() # returns sum of all elements

78

In [21]:
# To get sum of elements row wise "axis = 0"
np.sum(z,axis=0)
z.sum(0)
z.sum(axis=0)

#Note: returns same outputs

array([15, 18, 21, 24])

In [23]:
# To get sum of elements column wise "axis = 1"
np.sum(z,axis=1)
z.sum(1)
z.sum(axis=1)

#Note: returns same outputs

array([10, 26, 42])

In [24]:
# Initialization of arrays
a = np.array([1,2,3,4])
b = np.array([1,2,3,4])
print(a)
print(b)

[1 2 3 4]
[1 2 3 4]


#### Built-in Methods
- np.ones()-->Gives an array contains element '1'.By default 'float' type
- np.zeros()->Gives an array contains element '0'.By default 'float' type
- np.linspace()-->By default 'float' type.
- np.random.random()-->Creates random elements. By default 'float'
- np.arange()---------->By default 'int' type.
- np.full()-->Creates constant array of any number. Default 'int' type
- np.tile()-->Repeats array in sequence. By default 'int' type
- np.eye()--->Gives Identity matrix. By default 'float' type
- np.randint()--->Gives random array with specified range.By default 'int'

In [25]:
# np.ones()
a=np.ones((3,4), dtype = int)
print(a)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [26]:
a=np.ones((3,4))
print(a)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [28]:
a = np.ones((4,3), dtype=bool)
print(a)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [30]:
# np.zeros()
a = np.zeros([6,], dtype= int)
b = np.zeros([6,3], dtype= int)
print(a)
print(b)

[0 0 0 0 0 0]
[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


In [32]:
a = np.zeros([3,6])
print(a)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [34]:
a = np.zeros([3,6], dtype= bool)
print(a)

[[False False False False False False]
 [False False False False False False]
 [False False False False False False]]


In [35]:
# np.random()
a = np.random.random((3,4)) # prints random numbers
print(a)

[[0.16983797 0.72757708 0.40269535 0.3523853 ]
 [0.13442923 0.27589916 0.34578713 0.61999116]
 [0.5427436  0.16271176 0.96316176 0.11826241]]


In [36]:
a = np.random.random((4,4)) # prints random numbers
print(a)

[[0.89514666 0.47520036 0.75258063 0.01672179]
 [0.33727059 0.01319955 0.46711533 0.58168719]
 [0.06296868 0.46320765 0.2682539  0.86167595]
 [0.8076822  0.06947087 0.98233389 0.81162099]]


In [38]:
#np.linspace()
a = np.linspace(3,6,5, dtype=int)
#'3' & '6' is range of elements.
# '5' is number of elements
print(a)

b = np.linspace(1,4,7, dtype=int)
print(b)

[3 3 4 5 6]
[1 1 2 2 3 3 4]


In [40]:
# np.arange()
a = np.arange(1,13)
print(a)
b = np.arange(1,13, dtype=float)
print(b)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12.]


In [41]:
# np.full()
a =  np.full((3,4),8)
# (3,4) is (row,columns) & '8' is constant number
print(a)

[[8 8 8 8]
 [8 8 8 8]
 [8 8 8 8]]


In [44]:
a = np.full((3,4),'8', dtype=float)
# (3,4) is (row,columns) & 'a' is constant variable
print(a)
b = np.full((3,4),'a')
print(b)

[[8. 8. 8. 8.]
 [8. 8. 8. 8.]
 [8. 8. 8. 8.]]
[['a' 'a' 'a' 'a']
 ['a' 'a' 'a' 'a']
 ['a' 'a' 'a' 'a']]


In [48]:
# n.tile()
a = np.array([1,2,3])
print(np.tile(a,4))

a = np.array([1,2,3])
print(np.tile(a,(3,2)))
#'a' is array.In (3,2) '3' is row size. '2' is repeating twice

[1 2 3 1 2 3 1 2 3 1 2 3]
[[1 2 3 1 2 3]
 [1 2 3 1 2 3]
 [1 2 3 1 2 3]]


In [49]:
a = np.arange(1,7)
b = a.reshape(2,3)
c = np.tile(b,2)
print(c)

[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


In [57]:
# np.eye()
a = np.eye(3)
print(a)
print()
b = np.eye(4, dtype=int)
print(b)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [56]:
# np.randint()

a = np.random.randint(1,6,(3,3))
print(a)
print()
b = np.random.randint(1,9,(4,4))
print(b)

[[1 5 3]
 [5 1 1]
 [5 3 3]]

[[1 4 7 6]
 [6 3 8 3]
 [2 4 8 8]
 [5 2 2 7]]


- Difference b/w randint & random is:
- - random gives in b/w range of '0' & '1'. By default 'float'
- - randint gives any range of elements. By default 'int'